#!/usr/bin/env zsh

g++ \
  main.cpp \
  format_string.cpp \
  palindrome_check.cpp \
  email_check.cpp \
  email.cpp \
  password.cpp \
  str_util.cpp \
  simple_encrypt.cpp \
  -I /opt/local/include \
  -L /opt/local/lib \
  -l absl_str_format_internal \
  -std=c++20 \
  -o main