#!/usr/bin/env zsh

g++ -fPIC -c -std=c++20 \
  format_string.cpp \
  palindrome_check.cpp \
  email_check.cpp \
  email.cpp \
  password.cpp \
  str_util.cpp \
  simple_encrypt.cpp

g++ -shared -std=c++20 \
  format_string.o \
  palindrome_check.o \
  email_check.o \
  email.o \
  password.o \
  str_util.o \
  simple_encrypt.o \
  -o lib/libpizza.so